name: Create ServiceNow MMC change request
on: 
  workflow_dispatch:

jobs:
  changeApproval:
    name: ServiceNow Change Approval
    runs-on: ubuntu-latest
    steps:     
      - name: ServiceNow Change Approval
        uses: ServiceNow/servicenow-devops-change@main
        id: create
        with:
          devops-integration-user-name: ${{ secrets.SN_DEVOPS_USER }}
          devops-integration-user-password: ${{ secrets.SN_DEVOPS_PASSWORD }}
          instance-url: ${{ secrets.SN_INSTANCE_URL }}
          tool-id: ${{ secrets.SN_ORCHESTRATION_TOOL_ID }}
          context-github: ${{ toJSON(github) }}
          job-name: 'ServiceNow Change Approval'
          change-request: '{"setCloseCode":"true","attributes":{"assignment_group":"a715cd759f2002002920bde8132e7018"}}'
          interval: '100'
          timeout: '3600'
